---
- name: Prepare the odl controller for installation
  hosts: odl_controller
  tasks:
    - name: set hostname
      hostname:
          name: odl.redhat.local

    - name: update /etc/hosts with undercloud details
      lineinfile:
          dest: "/etc/hosts"
          line: "{{ ansible_default_ipv4.address }} odl.redhat.local odl"
          state: present

    - name: remove all repos
      command: "rm -f /etc/yum.repos.d/*"

    - name: install the rhos-release RPM
      shell: "yum localinstall -y {{ product.rpm }}"

    - debug:
          msg: "rhos-release {{ installer.version.major }}-director -p {{ installer.build }}"

    - name: create necessary repos with for director using rhos-release
      command: "rhos-release {{ installer.version.major }}-director -p {{ installer.build }}"
      register: command_result
      until: command_result.stderr.find('Connection reset by peer') == -1
      retries: 40
      delay: 5

    - debug:
          msg: "rhos-release {{ product.version.major }} -p {{ product.build }}"

    - name: create necessary repos for core using rhos-release
      command: "rhos-release {{ product.version.major }} -p {{ product.build }}"

    - name: update system packages
      yum:
          state: latest
          name: "*"
      register: update

    - name: reboot the odl controller
      shell: "sleep 2 && shutdown -r now"
      async: 1
      poll: 0
      ignore_errors: true
      when: update|changed

    - name: Waiting for the odl controller to be available
      delegate_to: localhost
      wait_for:
          host: "{{ hostvars[inventory_hostname].ansible_ssh_host }}"
          timeout: 120
      when: update|changed

- name: Install OpenDaylight distribution
  hosts: odl_controller
  sudo: yes
  tasks:
    - name: Install OpenDaylight distribution using RPM
      yum: name=opendaylight state=present

- name: Start OpenDaylight controller
  hosts: odl_controller
  sudo: yes
  vars:
      odl_controller_name: "{{ provisioner.topology.nodes.odl.name }}"
  tasks:
    - name: Enable traffic from OpenStack Controller to OpenDaylight node
      shell: iptables -I INPUT -j ACCEPT -p tcp -s {{ hostvars[provisioner.topology.nodes.odl.name].ansible_default_ipv4.address }}

    - name: Add L3 configuration
      shell: >
           echo "ovsdb.l3.fwd.enabled=yes" >> /opt/opendaylight/etc/custom.properties;
           eth0_mac_address={{ hostvars[odl_controller_name]['ansible_eth0']['macaddress'] }};
           echo "ovsdb.l3gateway.mac=$eth0_mac_address" >> /opt/opendaylight/etc/custom.properties

    - name: Run controller
      service: name=opendaylight state=started 
      async: 20

