---
- name: Attach ovs to an active opendaylight controller
  hosts: 
    - controller
    - compute
  sudo: yes
  tasks:
      - name: Start openvswitch
        service: name=openvswitch state=running

      - debug: msg={{  ansible_default_ipv4.address }}

      - name: Attach ovs to opendaylight controller
        command: ovs-vsctl set-manager tcp:{{  ansible_default_ipv4.address}}:6640

- name: Install repository for opendaylight driver
  hosts: controller
  sudo: yes
  tasks:
    - name: remove all repos
      command: "rm -f /etc/yum.repos.d/*"

    - name: install the rhos-release RPM
      shell: "yum localinstall -y {{ product.rpm }}"

    - debug:
          msg: "rhos-release {{ installer.version.major }}-director -p {{ installer.build }}"

    - name: create necessary repos with for director using rhos-release
      command: "rhos-release {{ installer.version.major }}-director -p {{ installer.build }}"
      register: command_result
      until: command_result.stderr.find('Connection reset by peer') == -1
      retries: 40
      delay: 5

    - debug:
          msg: "rhos-release {{ product.version.major }} -p {{ product.build }}"

    - name: create necessary repos for core using rhos-release
      command: "rhos-release {{ product.version.major }} -p {{ product.build }}"

- name: Install opendaylight driver using rpm
  hosts: controller
  sudo: yes
  tasks:
      - name: Install opendaylight driver
        yum: name=python-networking-odl state=latest
