---
- name: Start neutron-server
  hosts: controller
  sudo: yes
  tasks:
      - name: Start neutron-server service
        service: name=neutron-server
                 state=running

- name: External network creation
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: Get the controller nodes IPs
        shell: "source ~/stackrc; nova list | awk '/controller/ {print $12}' | grep -oP '[0-9.]+'"
        register: ip_list

      - name: get the default floating ip pool name from the controller
        shell: "ssh -o StrictHostKeyChecking=no -l heat-admin {{ ip_list.stdout_lines|last }} 'sudo grep -oP \"(?<=default_floating_pool=)(.*$)\" /etc/nova/nova.conf'"
        register: pool_name

      - name: create the external network
        shell: "source ~/overcloudrc; neutron net-create {{ pool_name.stdout_lines|last }} --router:external --provider:physical_network {{ installer.undercloud.config.physical_network }} --provider:network_type {{ installer.undercloud.config.network_type }}"

        # TODO: move the hard coded value to a variable
      - name: create the external subnet
        shell: "source ~/overcloudrc; neutron subnet-create {{ pool_name.stdout_lines|last }} 192.168.1.0/24 --name external_subnet --enable-dhcp=False --allocation-pool start=192.168.1.210,end=192.168.1.250 --gateway 192.168.1.1"
